#!/usr/bin/env python3
"""Refresh data/now.yaml from real repo activity (stdlib only).

Reads data/ci.yaml, queries the GitHub API for each workload's repo —
latest push time, head commit subject, latest completed Actions conclusion —
and writes data/now.yaml for the homepage status board.

Status mapping: Actions failure -> degraded; no pushes in 60 days -> idle
(rendered as operational but noted); otherwise operational.

Run locally (optionally with GITHUB_TOKEN for rate limits):
    python3 scripts/update_now.py
The deploy workflow runs this on every build and on a daily cron, so the
board tracks reality without committing anything.
"""

import datetime as dt
import json
import os
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CI = ROOT / "data" / "ci.yaml"
OUT = ROOT / "data" / "now.yaml"
API = "https://api.github.com"


def gh(path: str):
    req = urllib.request.Request(API + path, headers={
        "accept": "application/vnd.github+json",
        "user-agent": "pronei-portfolio-status",
        **({"authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"} if os.environ.get("GITHUB_TOKEN") else {}),
    })
    with urllib.request.urlopen(req, timeout=15) as res:
        return json.load(res)


def parse_ci():
    """Tiny purpose-built parser for data/ci.yaml's flat list-of-dicts shape."""
    rows, cur = [], None
    for raw in CI.read_text().splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip() or line.strip() == "workloads:":
            continue
        if line.lstrip().startswith("- "):
            cur = {}
            rows.append(cur)
            line = line.replace("- ", "  ", 1)
        if cur is not None and ":" in line:
            k, v = line.strip().split(":", 1)
            cur[k.strip()] = v.strip().strip('"')
    return rows


def rel(ts: str) -> str:
    then = dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))
    days = (dt.datetime.now(dt.timezone.utc) - then).days
    if days <= 0:
        return "today"
    if days == 1:
        return "yesterday"
    if days < 30:
        return f"{days}d ago"
    return f"{days // 30}mo ago"


def probe(repo: str):
    info = gh(f"/repos/{repo}")
    pushed = info["pushed_at"]
    subject = ""
    try:
        commits = gh(f"/repos/{repo}/commits?per_page=1")
        subject = commits[0]["commit"]["message"].split("\n")[0]
    except Exception:
        pass
    conclusion = None
    try:
        runs = gh(f"/repos/{repo}/actions/runs?per_page=1&status=completed")
        if runs.get("workflow_runs"):
            conclusion = runs["workflow_runs"][0]["conclusion"]
    except Exception:
        pass

    status = "operational"
    if conclusion in ("failure", "timed_out"):
        status = "degraded"
    note = subject[:46] + ("…" if len(subject) > 46 else "")
    parts = [p for p in (note, f"pushed {rel(pushed)}") if p]
    if conclusion:
        parts.append(f"ci {conclusion}")
    return status, " · ".join(parts)


def main() -> None:
    lines = [
        "# GENERATED by scripts/update_now.py from data/ci.yaml + the GitHub API.",
        "# Edit data/ci.yaml (not this file) to change rows.",
        f"updated: {dt.date.today().isoformat()}",
        "workloads:",
    ]
    for row in parse_ci():
        name, gloss, link = row.get("name", "?"), row.get("gloss", ""), row.get("link", "")
        status, note = row.get("status", "operational"), row.get("note", "")
        if row.get("repo"):
            try:
                status, note = probe(row["repo"])
            except Exception as e:
                note = f"status probe failed ({type(e).__name__})"
        lines += [
            f"  - name: {name}",
            f"    gloss: {gloss}",
            f"    note: {json.dumps(note)}",
            f"    status: {status}",
            f"    link: {link}",
        ]
        print(f"{name:14} {status:12} {note}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
